force-app/main/default/objects/AppLog__c.object
<CustomObject>
    <fields>
        <fullName>AffectedId__c</fullName>
        <description>Id of object(s) related to log event</description>
        <label>Affected Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogLevel__c</fullName>
        <label>LogLevel</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ShortMessage__c</fullName>
        <description>First 255 characters of message. Useful for SOQL WHERE clauses, and possibly GROUP BY</description>
        <label>Short Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>AppLog</label>
    <nameField>
        <label>AppLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LogUiController.cls
/**
 * @description 
 *
 * @author mikelockett 
 * @date 2020-03-16
 */

public without sharing class LogUiController {
	@AuraEnabled
	public static List<AppLog__c> getLogs(LogParamWrapper params) {
		System.debug(params);
		String query = 'SELECT AffectedId__c, Class__c, CreatedDate, '
				+ 'Id, LogLevel__c, Message__c, Name, ShortMessage__c '
				+ 'FROM AppLog__c '
				+ 'WHERE LogLevel__c IN :params.logLevels '
				+ ' ORDER BY CreatedDate DESC '
				+ ' LIMIT = ' + params.logsPerPage;
		List<AppLog__c> retVal = [
				SELECT AffectedId__c,
						Class__c,
						CreatedDate,
						Id,
						LogLevel__c,
						Message__c,
						Name,
						ShortMessage__c
				FROM AppLog__c
				WHERE LogLevel__c IN :params.logLevels
				ORDER BY CreatedDate DESC
				LIMIT :params.logsPerPage
		];
		return retVal;
	}

	@AuraEnabled
	public static List<AggregateResult> getLogCountByLevel(){
		List<AggregateResult> results = [
				SELECT COUNT(Id), MIN(CreatedDate), LogLevel__c
				FROM AppLog__c
				GROUP BY LogLevel__c
				ORDER BY LogLevel__c];
		return results;
	}

	public class LogParamWrapper {
		@AuraEnabled
		public List<String> logLevels { get; set; }
		public String cacheBuster { get; set; }
		@AuraEnabled
		public Integer logsPerPage { get; set; }
	}
}