src/objects/AppLog__c.object
<CustomObject>
    <fields>
        <fullName>AffectedId__c</fullName>
        <description>Id of object(s) related to log event</description>
        <label>Affected Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClassMethod__c</fullName>
        <label>Class/Method</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogLevel__c</fullName>
        <label>LogLevel</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <description>Active user</description>
        <label>UserId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>AppLog</label>
    <nameField>
        <label>AppLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AppLogEvent__e.object
<CustomObject>
    <fields>
        <fullName>AffectedId__c</fullName>
        <description>Ids for object(s) related to log event</description>
        <label>Affected Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClassMethod__c</fullName>
        <description>Class and method text</description>
        <label>Class/Method</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogLevel__c</fullName>
        <label>LogLevel</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <label>UserId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>AppLogEvent</label>
    <pluralLabel>AppLogEvents</pluralLabel>
</CustomObject>

force-app/main/default/objects/LogMessageFilter__mdt.object
<CustomObject>
    <description>Allow users to filter and replace content of log body using regular expressions</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RegexToFind__c</fullName>
        <description>Regex to to search for (can also use plain text)</description>
        <label>Regex to Find</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RegexToReplaceWith__c</fullName>
        <description>Regex to replace with in the event you use capture groups in Regex To Find field</description>
        <label>Regex To Replace With</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Log Message Filter</label>
    <pluralLabel>Log Message Filters</pluralLabel>
</CustomObject>

force-app/main/default/objects/LogRecordFilter__mdt.object
<CustomObject>
    <description>Determine what log levels are logged and optionally, for what users. Asterisk &quot;*&quot; means all users.
Note: log writing access levels are based on least-restrictive principal.</description>
    <fields>
        <fullName>Active_Log_User__c</fullName>
        <description>The log record filtering applies only when this user is the active user. Use * for all users.</description>
        <label>Active Log User</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicate whether this filter will be applied</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LogLevelCsv__c</fullName>
        <description>CSV of log levels to be logged.</description>
        <inlineHelpText>INFO, DEBUG, WARN, ERROR</inlineHelpText>
        <label>Log Levels CSV</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Log Record Filter</label>
    <pluralLabel>Log Record Filters</pluralLabel>
</CustomObject>

src/classes/LogService_Test.cls
/**
 * Created by mlockett on 6/16/2018.
 */
@IsTest
public with sharing class LogService_Test {

	@TestSetup
	static void testSetup() {
		LogService.testRecordFilters = new List<LogRecordFilter__mdt>();
		LogRecordFilter__mdt filter = new LogRecordFilter__mdt();
		filter.LogLevelCsv__c = 'INFO,DEBUG,WARN,ERROR';
		filter.Active_Log_User__c = '*';
		filter.Active__c = true;

		LogService.testRecordFilters.add(filter);
	}

	/**
	* verifies that determining ability to log does not throw when test recordFilters are not supplied
	*/
	@IsTest
	static void canQueryForLoggable() {
		// clear test values
		LogService.testRecordFilters = null;
		LogService.isLoggable(UserInfo.getUserId(), LoggingLevel.DEBUG);
	}

	@IsTest
	static void filtersLogRecordCorrectly() {
		testSetup();
		LogService.testRecordFilters[0].LogLevelCsv__c = 'INFO,WARN';

		Test.startTest();
		LogService.debug('My message', 'foo/method');
		Test.stopTest();

		List<AppLog__c> appLogs = [SELECT Id FROM AppLog__c];

		System.assertEquals(0, appLogs.size());
	}

	@IsTest
	static void filtersLogRecordCorrectlyWithNullFilter() {
		testSetup();
		LogService.testRecordFilters[0].LogLevelCsv__c = null;

		Test.startTest();
		LogService.debug('My message', 'foo/method');
		Test.stopTest();

		List<AppLog__c> appLogs = [SELECT Id FROM AppLog__c];

		System.assertEquals(0, appLogs.size());
	}

	@IsTest
	static void verifyFilter() {
		LogMessageFilter__mdt filter1 = new LogMessageFilter__mdt();
		filter1.RegexToReplaceWith__c = '***-**-$3';
		filter1.RegexToFind__c = '(\\d{3})-(\\d{2})-(\\d{4})';

		LogService.testMessageFilters = new List<LogMessageFilter__mdt>();//[filter1];
		LogService.testMessageFilters.add(filter1);

		String textToObscure = 'Hide the 123-12-1234 SSN.';
		String expectedText = 'Hide the ***-**-1234 SSN.';

		System.assertEquals(expectedText, LogService.filterString(textToObscure));
	}

	@IsTest
	static void logWritesCorrectValues() {

		LogService.ignoreTestMode = true;
		Test.startTest();
		LogService.log('My message', 'foo/method', LoggingLevel.WARN);
		Test.stopTest();

		AppLog__c appLog = [
				SELECT Message__c, LogLevel__c, UserId__c
				FROM AppLog__c
				WHERE ClassMethod__c = 'foo/method'
				LIMIT 1
		];

		System.assertEquals('My message', appLog.Message__c);
		System.assertEquals('WARN', appLog.LogLevel__c);
		System.assertEquals(UserInfo.getUserId(), appLog.UserId__c);
	}

	@IsTest
	static void debugWritesCorrectValues() {
		LogService.ignoreTestMode = true;
		Test.startTest();
		LogService.debug('My message', 'foo/method');
		Test.stopTest();

		AppLog__c appLog = [
				SELECT Message__c, LogLevel__c, UserId__c
				FROM AppLog__c
				WHERE ClassMethod__c = 'foo/method'
				LIMIT 1
		];

		System.assertEquals('My message', appLog.Message__c);
		System.assertEquals('DEBUG', appLog.LogLevel__c);
		System.assertEquals(UserInfo.getUserId(), appLog.UserId__c);
	}

	@IsTest
	static void warnWritesCorrectValues() {
		LogService.ignoreTestMode = true;
		Test.startTest();
		LogService.warn('My message', 'foo/method');
		Test.stopTest();

		AppLog__c appLog = [
				SELECT Message__c, LogLevel__c, UserId__c
				FROM AppLog__c
				WHERE ClassMethod__c = 'foo/method'
				LIMIT 1
		];

		System.assertEquals('My message', appLog.Message__c);
		System.assertEquals('WARN', appLog.LogLevel__c);
		System.assertEquals(UserInfo.getUserId(), appLog.UserId__c);
	}

	@IsTest
	static void errorWritesCorrectValues() {
		LogService.ignoreTestMode = true;
		Test.startTest();
		LogService.error('My message', 'foo/method');
		Test.stopTest();

		AppLog__c appLog = [
				SELECT Message__c, LogLevel__c, UserId__c
				FROM AppLog__c
				WHERE ClassMethod__c = 'foo/method'
				LIMIT 1
		];

		System.assertEquals('My message', appLog.Message__c);
		System.assertEquals('ERROR', appLog.LogLevel__c);
		System.assertEquals(UserInfo.getUserId(), appLog.UserId__c);
	}

	@IsTest
	static void errorWritesCorrectValuesForException() {
		LogService.ignoreTestMode = true;
		Test.startTest();
		try {
			//noinspection ApexUnusedDeclaration
			Double badNumber = 1 / 0; // force MathException
		} catch (Exception ex) {
			LogService.error(ex, 'foo/method');
		}

		Test.stopTest();

		AppLog__c appLog = [
				SELECT Message__c, LogLevel__c, UserId__c
				FROM AppLog__c
				WHERE ClassMethod__c = 'foo/method'
				LIMIT 1
		];

		System.assert(appLog.Message__c.startsWith('Exception - Type: System.MathException;'));
		System.assertEquals('ERROR', appLog.LogLevel__c);
		System.assertEquals(UserInfo.getUserId(), appLog.UserId__c);
	}

	@IsTest
	static void errorWithIdWritesCorrectValuesForException() {
		LogService.ignoreTestMode = true;
		Test.startTest();
		try {
			//noinspection ApexUnusedDeclaration
			Double badNumber = 1 / 0; // force MathException
		} catch (Exception ex) {
			LogService.error(ex, 'foo/method', 'my id');
		}

		Test.stopTest();

		AppLog__c appLog = [
				SELECT Message__c, LogLevel__c, UserId__c, AffectedId__c
				FROM AppLog__c
				WHERE ClassMethod__c = 'foo/method'
				LIMIT 1
		];

		System.assert(appLog.Message__c.startsWith('Exception - Type: System.MathException;'));
		System.assertEquals('ERROR', appLog.LogLevel__c);
		System.assertEquals('my id', appLog.AffectedId__c);
		System.assertEquals(UserInfo.getUserId(), appLog.UserId__c);
	}

	@IsTest
	static void logWritesCorrectValuesForException() {
		LogService.ignoreTestMode = true;
		Test.startTest();
		try {
			//noinspection ApexUnusedDeclaration
			Double badNumber = 1 / 0; // force MathException
		} catch (Exception ex) {
			LogService.log(ex, 'foo/method', LoggingLevel.DEBUG);
		}

		Test.stopTest();

		AppLog__c appLog = [
				SELECT Message__c, LogLevel__c, UserId__c
				FROM AppLog__c
				WHERE ClassMethod__c = 'foo/method'
				LIMIT 1
		];

		System.assert(appLog.Message__c.startsWith('Exception - Type: System.MathException;'));
		System.assertEquals('DEBUG', appLog.LogLevel__c);
		System.assertEquals(UserInfo.getUserId(), appLog.UserId__c);
	}

	@IsTest
	static void errorDoesNotThrow() {
		String tooLong = '12345678901234567890123456789012345678901234567890'
				+ '12345678901234567890123456789012345678901234567890'
				+ '12345678901234567890123456789012345678901234567890'
				+ '12345678901234567890123456789012345678901234567890';
		Test.startTest();
		LogService.warn('errorDoesNotThrow_message', tooLong);
		Test.stopTest();

		List<AppLog__c> appLogs = [
				SELECT Message__c, LogLevel__c, UserId__c
				FROM AppLog__c
				WHERE LogLevel__c = 'WARN'
				LIMIT 1
		];
		System.assertEquals(0, appLogs.size());

	}

	@IsTest
	static void logFailsSansIgnoreTestMode() {
		Test.startTest();
		LogService.log('My message', 'foo/method', LoggingLevel.DEBUG);
		Test.stopTest();

		List<AppLog__c> appLogs = [
				SELECT Message__c, LogLevel__c, UserId__c
				FROM AppLog__c
				WHERE ClassMethod__c = 'foo/method'
				LIMIT 1
		];

		System.assertEquals(0, appLogs.size());
	}

	@IsTest
	static void badEventGeneratesError() {
		LogService.ignoreTestMode = true;
		String tooLong = '12345678901234567890123456789012345678901234567890'
				+ '12345678901234567890123456789012345678901234567890'
				+ '12345678901234567890123456789012345678901234567890'
				+ '12345678901234567890123456789012345678901234567890';
		AppLogEvent__e event = new AppLogEvent__e();
		event.ClassMethod__c = tooLong;
		List<Database.Error> errors = LogService.publishEvent(event);
		System.assertEquals(1, errors.size());
	}
}